name: Generate Product Index

on:
  push:
    paths:
      - "stock/**"
      - ".github/workflows/generate-index.yml"
  workflow_dispatch:

jobs:
  generate-index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Generate Index
        run: python scripts/generate_index.py

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add stock/index.json
          git commit -m "Update product index" || echo "No changes to commit"
          git push
